version: '3'

services:
  db:
    container_name: postgres
    image: mdillon/postgis:11-alpine
    ports:
     - "5429:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
 
  server:
    env_file: .env
    container_name: server
    image: apidemo:1.0.1
    build: .
    restart: on-failure
    command: bash -c "npm install nodemon && npm run hotload"
    ports:
      - "8000:3000"
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db